import os
from tools.configs import NODE_DATA_PATH, CONFIG_FOLDER

SCHAINS_DIR_NAME = 'schains'
SCHAINS_DIR_PATH = os.path.join(NODE_DATA_PATH, SCHAINS_DIR_NAME)

SCHAIN_OWNER_ALLOC = 1000000000000000000000 # todo: tmp!
NODE_OWNER_ALLOC = 1000000000000000000000  # todo: tmp!

DATA_DIR_NAME = 'data_dir'

BASE_SCHAIN_CONFIG_FILENAME = 'schain_base_config.json'
BASE_SCHAIN_CONFIG_FILEPATH = os.path.join(CONFIG_FOLDER, BASE_SCHAIN_CONFIG_FILENAME)
