name: Test
on: [push, pull_request]
env:
  ETH_PRIVATE_KEY: ${{ secrets.ETH_PRIVATE_KEY }}
  SCHAIN_TYPE: ${{ secrets.SCHAIN_TYPE }}
  MANAGER_TAG: "1.5.2-develop.20"
  SGX_WALLET_TAG: "1.58.0-develop.5"
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  PYTHON_VERSION: 3.8
jobs:
  test_core:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master
      with:
        remote: true
    - name: Install python dependencies
      run: bash ./scripts/install_python_dependencies.sh
    - name: Lint with flake8
      run: flake8 .
    - name: Deploy manager contracts
      run: |
        bash ./helper-scripts/deploy_manager.sh
    # - name: Run core tests
    #   run: |
    #     bash ./scripts/run_core_tests.sh
    - name: Run codecov
      run: |
        codecov -t $CODECOV_TOKEN
  test_rotation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master
      with:
        remote: true
    - name: Install python dependencies
      run: bash ./scripts/install_python_dependencies.sh
    - name: Deploy manager contracts
      run: |
        bash ./helper-scripts/deploy_manager.sh
    # - name: Run core tests
    #   run: |
    #     bash ./scripts/run_rotation_tests.sh
