name: Test

on: [push]

env:
  ETH_PRIVATE_KEY: ${{ secrets.ETH_PRIVATE_KEY }}
  SCHAIN_TYPE: ${{ secrets.SCHAIN_TYPE }}
  MANAGER_TAG: "1.12.0-develop.21"
  IMA_TAG: "2.3.0-beta.3"
  SGX_WALLET_TAG: "1.10.1-develop.5"
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  PYTHON_VERSION: 3.13

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test_fair:
    runs-on: ubuntu-22.04
    env:
      ENDPOINT: http://127.0.0.1:1234
      FAIR_TAG: "0.0.1-develop.50"
      SKALED_TAG: 4.1.0-develop.24-mirage

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Set up Python 3.13
        run: uv python install 3.13

      - name: Install python dependencies
        run: uv sync --prerelease=allow --all-extras

      - name: Checking formatting with ruff
        run: uv run ruff check

      - name: Cleanup artifacts
        if: always()
        run: |
          rm -r tests/schain-data/.artifacts/skaled-datadir || true
          rm -r helper-scripts/contracts_data || true

      - name: Launch hardhat node
        run: |
          bash ./helper-scripts/helper.sh run_hh_node

      - name: Run sgx wallet sim
        run: |
          bash ./scripts/run_sgxwallet.sh

      - name: Run skaled
        run: |
          bash ./scripts/run_skaled.sh

      - name: Deploy manager
        run: |
          bash ./helper-scripts/deploy_manager.sh
          docker rmi -f skalenetwork/skale-manager:${{ env.MANAGER_TAG }}

      - name: Show stats before tests
        if: always()
        run: |
          lsblk -f
          free -h

      - name: Run core tests
        run: |
          bash ./scripts/run_fair_test.sh

      - name: Cleanup build artifacts
        if: always()
        run: |
          docker rm -f $(docker ps -aq)
          rm -r tests/schain-data/.artifacts/skaled-datadir || true
          rm helper-scripts/private_key.txt || true

      - name: Show stats after core tests
        if: always()
        run: |
          lsblk -f
          free -h

  test_core:
    needs: [test_fair]
    runs-on: ubuntu-22.04
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      SCHAIN_TYPE: ${{ secrets.SCHAIN_TYPE }}
      ENDPOINT: http://127.0.0.1:8545
      # RUN_ANVIL: true
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Set up Python 3.13
        run: uv python install 3.13

      - name: Install python dependencies
        run: |
          uv sync --prerelease=allow --all-extras

      - name: Checking formatting with ruff
        run: uv run ruff check

      - name: Launch hardhat node
        run: |
          bash ./helper-scripts/helper.sh run_hh_node

      - name: Run sgx wallet sim
        run: |
          bash ./scripts/run_sgxwallet.sh

      - name: Deploy manager
        run: |
          bash ./helper-scripts/deploy_manager.sh
          docker rmi -f skalenetwork/skale-manager:${{ env.MANAGER_TAG }}

      - name: Deploy IMA
        run: |
          bash ./helper-scripts/deploy_ima.sh
          docker rmi -f skalenetwork/ima-contracts:${{ env.IMA_TAG }}

      - name: Show stats before tests
        if: always()
        run: |
          lsblk -f
          free -h

      - name: Run core tests
        run: |
          bash ./scripts/run_core_tests.sh --durations=0 -v

      - name: Cleanup docker artifacts
        run: |
          docker rm -f $(docker ps -aq)

      - name: Show stats after core tests
        if: always()
        run: |
          lsblk -f
          free -h

      - name: Run firewall tests
        run: |
          bash ./scripts/run_firewall_test.sh

      - name: Show stats after firewall tests
        if: always()
        run: |
          lsblk -f
          free -h

      - name: Cleanup build artifacts
        if: always()
        run: |
          docker rm -f $(docker ps -aq)
          rm helper-scripts/private_key.txt || true

      - name: Run codecov
        run: |
          uv run codecov -t $CODECOV_TOKEN
