name: Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ETH_PRIVATE_KEY: ${{ secrets.ETH_PRIVATE_KEY }}
      ENDPOINT: ${{ secrets.ENDPOINT }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      IMA_ENDPOINT: ${{ secrets.IMA_ENDPOINT }}
      SCHAIN_TYPE: ${{ secrets.SCHAIN_TYPE }}
      MANAGER_TAG: "1.7.1-develop.4"
      SGX_WALLET_TAG: "1.59.1-stable.6"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip uninstall pycrypto -y
        pip uninstall pycryptodome -y
        pip install pycryptodome
        find . -name "*.pyc" -exec rm -f {} \;
    - name: Lint with flake8
      run: |
        flake8 .
    - name: Deploy manager contracts
      run: |
        bash ./scripts/deploy_manager.sh
    - name: Run tests
      run: |
        bash ./scripts/run_tests.sh
    - name: Codecov
      run: |
        codecov -t $CODECOV_TOKEN
