name: Test
on: [push, pull_request]
env:
  ETH_PRIVATE_KEY: ${{ secrets.ETH_PRIVATE_KEY }}
  SCHAIN_TYPE: ${{ secrets.SCHAIN_TYPE }}
  MANAGER_TAG: "1.9.3-beta.0"
  IMA_TAG: "1.3.4-beta.5"
  SGX_WALLET_TAG: "1.83.0-beta.5"
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  PYTHON_VERSION: 3.8
jobs:
  test_core:
    runs-on: ubuntu-latest
    env:
      ETH_PRIVATE_KEY: ${{ secrets.ETH_PRIVATE_KEY }}
      ENDPOINT: http://127.0.0.1:8545
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      IMA_ENDPOINT: ${{ secrets.IMA_ENDPOINT }}
      SCHAIN_TYPE: ${{ secrets.SCHAIN_TYPE }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install python dependencies
        run: bash ./scripts/install_python_dependencies.sh
      - name: Lint with flake8
        run: flake8 .
      - name: Launch hardhat node
        working-directory: hardhat-node
        run: |
          docker-compose up -d 
          docker pull skalenetwork/ima:2.0.0-beta.9
      - name: Deploy manager & ima contracts
        run: |
          bash ./helper-scripts/deploy_test_ima.sh
      - name: Run core tests
        run: |
          bash ./scripts/run_core_tests.sh
      - name: Run codecov
        run: |
          codecov -t $CODECOV_TOKEN
